export const CALL_FOR_TODO = "CALL_FOR_TODO"
export const STORE_TODO = "STORE_TODO"
export const ADD_TODOS = "ADD_TODOS"
export const DELETE_TODOS = "DELETE_TODOS"
export const UPDATE_TODOS = "UPDATE_TODOS"